packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - 'docs/'
  - 'demo/'
  - 'storybook/'
allowBuilds:
  esbuild: true # insurance for core build
  '@parcel/watcher': false
  netlify-cli: false
  sharp: false
  unix-dgram: false
