packages:
  # include packages in subfolders (e.g. apps/ and packages/)
  - 'docs/'
  - 'demo/'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  netlify-cli: false
  sharp: false
  unix-dgram: false
